export const PROGRAMS: string[] = [
  "Accounting",
  "Anthropology",
  "Applied Mathematics",
  "Architecture",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Comparative Literature",
  "Computer Science",
  "Criminal Justice",
  "Data Science",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Environmental Science",
  "Finance",
  "Fine Arts",
  "Graphic Design",
  "History",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Law",
  "Linguistics",
  "Marketing",
  "Mechanical Engineering",
  "Music",
  "Nursing",
  "Nutrition and Dietetics",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Sociology",
  "Software Engineering",
  "Theatre and Drama",
];
