/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as StudentsIdEditRouteImport } from './routes/students.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdEditRoute = StudentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StudentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/students/$id': typeof StudentsIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/students/$id': typeof StudentsIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/students/$id': typeof StudentsIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/students/$id' | '/students/new' | '/students/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/students/$id' | '/students/new' | '/students/$id/edit'
  id:
    '__root__' | '/' | '/students/$id' | '/students/new' | '/students/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentsIdRoute: typeof StudentsIdRouteWithChildren
  StudentsNewRoute: typeof StudentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/edit': {
      id: '/students/$id/edit'
      path: '/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof StudentsIdEditRouteImport
      parentRoute: typeof StudentsIdRoute
    }
  }
}

interface StudentsIdRouteChildren {
  StudentsIdEditRoute: typeof StudentsIdEditRoute
}

const StudentsIdRouteChildren: StudentsIdRouteChildren = {
  StudentsIdEditRoute: StudentsIdEditRoute,
}

const StudentsIdRouteWithChildren = StudentsIdRoute._addFileChildren(
  StudentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentsIdRoute: StudentsIdRouteWithChildren,
  StudentsNewRoute: StudentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
